import { createClient } from "contentful";
import type { NextPage } from "next";
import Head from "next/head";
import ProjectCard from "../components/ProjectCard";
import styled from "styled-components";

const Grid = styled.section`
  display: grid;
  width: 100%;
  grid-template-columns: repeat(auto-fit, minmax(150px, 1fr));
`;

export const getStaticProps = async () => {
  const client = createClient({
    space: process.env.CONTENTFUL_SPACE_ID || "",
    accessToken: process.env.CONTENTFUL_ACCESS_KEY || "",
  });

  const res = await client.getEntries({
    content_type: "project",
  });

  return {
    props: {
      projects: res.items,
    },
  };
};

const Home: NextPage<any, any> = ({ projects }) => {
  console.log(projects);

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Grid>
          {projects
            .filter(({ fields }: any) => fields.tags === "selected")
            .map(({ fields, sys }: any) => (
              <ProjectCard key={sys.id} {...fields} />
            ))}
        </Grid>
      </main>
    </div>
  );
};

export default Home;
